services:
  LuxuryHomeAbidjan-Production:
    env_file:
      - .env.local
    build:
      context: .
      args:
        NEXT_PUBLIC_URL: ${NEXT_PUBLIC_URL}
        NEXT_PUBLIC_API_BACKEND_URL: ${NEXT_PUBLIC_API_BACKEND_URL}
        NEXT_PUBLIC_API_FILE_URL: ${NEXT_PUBLIC_API_FILE_URL}
    image: chicken-nation-web-prod
    ports:
      - "${DOCKER_PORT}:3000"